Map<int, String> bunyiPasal = {
  77: """Setiap orang yang dengan sengaja melakukan tindakan :\na. diskriminasi terhadap anak yang mengakibatkan anak mengalami kerugian, baik materiil maupun moril sehingga menghambat fungsi sosialnya; atau\nb. penelantaran terhadap anak yang mengakibatkan anak mengalami sakit atau penderitaan, baik fisik, mental, maupun sosial,\nc. dipidana dengan pidana penjara paling lama 5 (lima) tahun dan/atau denda paling banyak Rp 100.000.000,00 (seratus juta rupiah).\n""",
  78: """Setiap orang yang mengetahui dan sengaja membiarkan anak dalam situasi darurat sebagaimana dimaksud dalam Pasal 60,anak yang berhadapan dengan hukum, anak dari kelompok minoritas dan terisolasi, anak yang tereksploitasi secara ekonomi dan/atau seksual, anak yang diperdagangkan,anak yang menjadi korban penyalahgunaan narkotika, alkohol, psikotropika, dan zat adiktif lainnya (napza), anak korban penculikan, anak korban perdagangan, atau anak korban kekerasansebagaimana dimaksud dalam Pasal 59, padahal anak tersebut memerlukan pertolongan dan harus dibantu, dipidana dengan pidana penjara paling lama 5 (lima) tahun dan/atau denda paling banyak Rp 100.000.000,00 (seratus juta rupiah).\n""",
  79: """Setiap orang yang melakukan pengangkatan anak yang bertentangandengan ketentuan sebagaimana dimaksud dalam Pasal 39 ayat (1), ayat(2), dan ayat (4), dipidana dengan pidana penjara paling lama 5 (lima)tahun dan/atau denda paling banyak Rp 100.000.000,00 (seratus juta rupiah).\n""",
  80: """(1) Setiap orang yang melakukan kekejaman, kekerasan atau ancamankekerasan, atau penganiayaan terhadap anak, dipidana denganpidana penjara paling lama 3 (tiga) tahun 6 (enam) bulan dan/ataudenda paling banyak Rp 72.000.000,00 (tujuh puluh dua jutarupiah).\n(2)Dalam hal anak sebagaimana dimaksud dalam ayat (1) luka berat,maka pelaku dipidana dengan pidana penjara paling lama 5 (lima)tahun dan/atau denda paling banyak Rp 100.000.000,00 (seratusjuta rupiah).\n(3)Dalam hal anak sebagaimana dimaksud dalam ayat (2) mati, makapelaku dipidana dengan pidana penjara paling lama 10 (sepuluh)tahun dan/atau denda paling banyak Rp 200.000.000,00 (dua ratusjuta rupiah).\n(4)Pidana ditambah sepertiga dari ketentuan sebagaimana dimaksuddalam ayat (1), ayat (2), dan ayat (3) apabila yang melakukanpenganiayaan tersebut orang tuanya.\n""",
  81: """(1) Setiap orang yang dengan sengaja melakukan kekerasan atau ancaman kekerasan memaksa anak melakukan persetubuhandengannya atau dengan orang lain, dipidana dengan pidana penjara paling lama 15 (lima belas) tahun dan paling singkat 3 (tiga) tahundan denda paling banyak Rp 300.000.000,00 (tiga ratus juta rupiah) dan paling sedikit Rp 60.000.000,00 (enam puluh juta rupiah).\n(2) Ketentuan pidana sebagaimana dimaksud dalam ayat (1) berlakupula bagi setiap orang yang dengan sengaja melakukan tipumuslihat, serangkaian kebohongan, atau membujuk anak melakukanpersetubuhan dengannya atau dengan orang lain.\n""",
  82: """Setiap orang yang dengan sengaja melakukan kekerasan atau ancamankekerasan, memaksa, melakukan tipu muslihat, serangkaiankebohongan, atau membujuk anak untuk melakukan atau membiarkandilakukan perbuatan cabul, dipidana dengan pidana penjara paling lama15 (lima belas) tahun dan paling singkat 3 (tiga) tahun dan denda palingbanyak Rp 300.000.000,00 (tiga ratus juta rupiah) dan paling sedikit Rp60.000.000,00 (enam puluh juta rupiah).\n""",
  83: """Setiap orang yang memperdagangkan, menjual, atau menculik anak untuk diri sendiri atau untuk dijual, dipidana dengan pidana penjara paling lama 15 (lima belas) tahun dan paling singkat 3 (tiga) tahun dan denda paling banyak Rp 300.000.000,00 (tiga ratus juta rupiah) dan paling sedikit Rp 60.000.000,00 (enam puluh juta rupiah).\n""",
  84: """Setiap orang yang secara melawan hukum melakukan transplantasi organ dan/atau jaringan tubuh anak untuk pihak lain dengan maksud untuk menguntungkan diri sendiri atau orang lain, dipidana dengan pidana penjara paling lama 10 (sepuluh) tahun dan/atau denda paling banyak Rp 200.000.000,00 (dua ratus juta rupiah).\n""",
  85: """(1) Setiap orang yang melakukan jual beli organ tubuh dan/atau jaringan tubuh anak dipidana dengan pidana penjara paling lama 15 (lima belas) tahun dan/atau denda paling banyak Rp 300.000.000,00 (tiga ratus juta rupiah).\n(2) Setiap orang yang secara melawan hukum melakukan pengambilan organ tubuh dan/atau jaringan tubuh anak tanpa memperhatikan kesehatan anak, atau penelitian kesehatan yang menggunakan anak sebagai objek penelitian tanpa seizin orang tua atau tidak mengutamakan kepentingan yang terbaik bagi anak, dipidana dengan pidana penjara paling lama 10 (sepuluh) tahun dan/atau denda paling banyak Rp 200.000.000,00 (dua ratus juta rupiah).\n""",
  86: """Setiap orang yang dengan sengaja menggunakan tipu muslihat, rangkaian kebohongan, atau membujuk anak untuk memilih agama lain bukan atas kemauannya sendiri, padahal diketahui atau patut diduga bahwa anak tersebut belum berakal dan belum bertanggung jawab sesuai dengan agama yang dianutnya dipidana dengan pidana penjara paling lama 5 (lima) tahun dan/atau denda paling banyak Rp 100.000.000,00 (seratus juta rupiah).\n""",
  87: """Setiap orang yang secara melawan hukum merekrut atau memperalat anak untuk kepentingan militer sebagaimana dimaksud dalam Pasal 63 atau penyalahgunaan dalam kegiatan politik atau pelibatan dalam sengketa bersenjata atau pelibatan dalam kerusuhan sosial atau pelibatan dalam peristiwa yang mengandung unsur kekerasan atau pelibatan dalam peperangan sebagaimana dimaksud dalam Pasal 15 dipidana dengan pidana penjara paling lama 5 (lima) tahun dan/atau denda paling banyak Rp 100.000.000,00 (seratus juta rupiah).\n""",
  89: """(1) Setiap orang yang dengan sengaja menempatkan, membiarkan, melibatkan, menyuruh melibatkan anak dalam penyalahgunaan, produksi atau distribusi narkotika dan/atau psikotropika dipidana dengan pidana mati atau pidana penjara seumur hidup atau pidana penjara paling lama 20 (dua puluh) tahun dan pidana penjara paling singkat 5 (lima) tahun dan denda paling banyak Rp 500.000.000,00 (lima ratus juta rupiah) dan paling sedikit Rp 50.000.000,00 (lima puluh juta rupiah).\n(2) Setiap orang yang dengan sengaja menempatkan, membiarkan, melibatkan, menyuruh melibatkan anak dalam penyalahgunaan, produksi, atau distribusi alkohol dan zat adiktif lainnya dipidana dengan pidana penjara paling lama 10 (sepuluh) tahun dan paling singkat 2 (dua) tahun dan denda paling banyak Rp 200.000.000,00 (dua ratus juta rupiah) dan denda paling sedikit Rp 20.000.000,00 (dua puluh juta rupiah).\n""",
};
